### ISSUE TITLE
404 from About page

### ISSUE THREAD

**Issue by bambooforest** [langcog/childes-db-website#26]
https://childes-db.stanford.edu/about.html

The `childesr` link is broken (https://cran.r-project.org/web/packages/childesr/childesr.pdf):

https://github.com/langcog/childes-db-website/blob/4d2d3b0767fde783c893c6c6f2ff59f682b34db0/about.html#L13

I'd submit a PR, but I'm not sure what it should be given that the package seems to have been removed from cran:

https://cran.r-project.org/web/packages/childesr/index.html

**Comment by mikabr** [comment]
no longer an issue
