### ISSUE TITLE
name of repo is confusing

### ISSUE THREAD

**Issue by mcfrank** [langcog/childes-db-website#3]
could change to `childes-db-website` by virtue of `childes-db-shiny` but we should discuss repo organization as we now have:

website: `langcog/childes-db`
db: `smeylan/childes-db`
shiny apps: `mcfrank/childes-db-shiny`
r package: `langcog/childesr`

do we want all of these on the same organiazation?

**Comment by amsan7** [comment]
agree that they should all belong to the same organization. @smeylan what do you think? should we transfer the repo to langcog?

**Comment by amsan7** [comment]
@mcfrank i changed the repo name, but now the website is https://langcog.github.io/childes-db-website/. should we point childes-db.stanford.edu to this site? (info [here](https://help.github.com/articles/using-a-custom-domain-with-github-pages/))

**Comment by mcfrank** [comment]
requested

Mike

**Comment by mcfrank** [comment]
working, should we close?

**Comment by amsan7** [comment]
yeah
